require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DailyQuestionsController do

  # This should return the minimal set of attributes required to create a valid
  # DailyQuestion. As you add validations to DailyQuestion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "question" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DailyQuestionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all daily_questions as @daily_questions" do
      daily_question = DailyQuestion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:daily_questions).should eq([daily_question])
    end
  end

  describe "GET show" do
    it "assigns the requested daily_question as @daily_question" do
      daily_question = DailyQuestion.create! valid_attributes
      get :show, {:id => daily_question.to_param}, valid_session
      assigns(:daily_question).should eq(daily_question)
    end
  end

  describe "GET new" do
    it "assigns a new daily_question as @daily_question" do
      get :new, {}, valid_session
      assigns(:daily_question).should be_a_new(DailyQuestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested daily_question as @daily_question" do
      daily_question = DailyQuestion.create! valid_attributes
      get :edit, {:id => daily_question.to_param}, valid_session
      assigns(:daily_question).should eq(daily_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DailyQuestion" do
        expect {
          post :create, {:daily_question => valid_attributes}, valid_session
        }.to change(DailyQuestion, :count).by(1)
      end

      it "assigns a newly created daily_question as @daily_question" do
        post :create, {:daily_question => valid_attributes}, valid_session
        assigns(:daily_question).should be_a(DailyQuestion)
        assigns(:daily_question).should be_persisted
      end

      it "redirects to the created daily_question" do
        post :create, {:daily_question => valid_attributes}, valid_session
        response.should redirect_to(DailyQuestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved daily_question as @daily_question" do
        # Trigger the behavior that occurs when invalid params are submitted
        DailyQuestion.any_instance.stub(:save).and_return(false)
        post :create, {:daily_question => { "question" => "invalid value" }}, valid_session
        assigns(:daily_question).should be_a_new(DailyQuestion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DailyQuestion.any_instance.stub(:save).and_return(false)
        post :create, {:daily_question => { "question" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested daily_question" do
        daily_question = DailyQuestion.create! valid_attributes
        # Assuming there are no other daily_questions in the database, this
        # specifies that the DailyQuestion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DailyQuestion.any_instance.should_receive(:update).with({ "question" => "MyString" })
        put :update, {:id => daily_question.to_param, :daily_question => { "question" => "MyString" }}, valid_session
      end

      it "assigns the requested daily_question as @daily_question" do
        daily_question = DailyQuestion.create! valid_attributes
        put :update, {:id => daily_question.to_param, :daily_question => valid_attributes}, valid_session
        assigns(:daily_question).should eq(daily_question)
      end

      it "redirects to the daily_question" do
        daily_question = DailyQuestion.create! valid_attributes
        put :update, {:id => daily_question.to_param, :daily_question => valid_attributes}, valid_session
        response.should redirect_to(daily_question)
      end
    end

    describe "with invalid params" do
      it "assigns the daily_question as @daily_question" do
        daily_question = DailyQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DailyQuestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => daily_question.to_param, :daily_question => { "question" => "invalid value" }}, valid_session
        assigns(:daily_question).should eq(daily_question)
      end

      it "re-renders the 'edit' template" do
        daily_question = DailyQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DailyQuestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => daily_question.to_param, :daily_question => { "question" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested daily_question" do
      daily_question = DailyQuestion.create! valid_attributes
      expect {
        delete :destroy, {:id => daily_question.to_param}, valid_session
      }.to change(DailyQuestion, :count).by(-1)
    end

    it "redirects to the daily_questions list" do
      daily_question = DailyQuestion.create! valid_attributes
      delete :destroy, {:id => daily_question.to_param}, valid_session
      response.should redirect_to(daily_questions_url)
    end
  end

end
